export const featuredRows = [
  {
    id: "spring-refresh",
    title: "Spring Refresh",
    items: [
      {
        id: "spring-1",
        title: "Irresistible Grace Painting",
        artist: "Murray Taylor, United States",
        medium: "Oil On Canvas",
        size: "91.4 × 121.9 cm",
        price: "C$7,140",
        image: "https://picsum.photos/seed/spring-1/520/680",
      },
      {
        id: "spring-2",
        title: "Whisper XVI Painting",
        artist: "Tomek Mistak, Poland",
        medium: "Acrylic On Canvas",
        size: "110 × 90 cm",
        price: "C$3,577",
        image: "https://picsum.photos/seed/spring-2/520/680",
      },
      {
        id: "spring-3",
        title: "Ending At Every Moment Painting",
        artist: "Murray Taylor, United States",
        medium: "Oil On Canvas",
        size: "127 × 127 cm",
        price: "C$7,728",
        image: "https://picsum.photos/seed/spring-3/520/680",
      },
      {
        id: "spring-4",
        title: "How To Disappear Completely Painting",
        artist: "Bjarni Aaslund, Norway",
        medium: "Acrylic On Canvas",
        size: "170 × 110 cm",
        price: "C$9,643",
        image: "https://picsum.photos/seed/spring-4/520/680",
      },
      {
        id: "spring-5",
        title: "Splash Painting",
        artist: "Mark Rauschberg, Austria",
        medium: "Oil On Canvas",
        size: "60 × 70 cm",
        price: "C$3,059",
        image: "https://picsum.photos/seed/spring-5/520/680",
      },
      {
        id: "spring-6",
        title: "Morning Cloud Painting",
        artist: "Elena Fraser, Canada",
        medium: "Oil On Linen",
        size: "100 × 120 cm",
        price: "C$5,940",
        image: "https://picsum.photos/seed/spring-6/520/680",
      },
      {
        id: "spring-7",
        title: "Quiet Horizon Painting",
        artist: "Dario Voss, Germany",
        medium: "Acrylic On Canvas",
        size: "90 × 90 cm",
        price: "C$2,860",
        image: "https://picsum.photos/seed/spring-7/520/680",
      },
      {
        id: "spring-8",
        title: "Water Garden Painting",
        artist: "Anne Dubois, France",
        medium: "Mixed Media On Canvas",
        size: "120 × 100 cm",
        price: "C$6,310",
        image: "https://picsum.photos/seed/spring-8/520/680",
      },
      {
        id: "spring-9",
        title: "Open Sky Painting",
        artist: "Luca Ferri, Italy",
        medium: "Oil On Canvas",
        size: "80 × 100 cm",
        price: "C$4,180",
        image: "https://picsum.photos/seed/spring-9/520/680",
      },
      {
        id: "spring-10",
        title: "Blue Current Painting",
        artist: "Nina Berg, Sweden",
        medium: "Acrylic On Canvas",
        size: "95 × 110 cm",
        price: "C$3,920",
        image: "https://picsum.photos/seed/spring-10/520/680",
      },
    ],
  },
  {
    id: "light-bright",
    title: "Light & Bright",
    items: [
      {
        id: "light-1",
        title: "Oleron 10 Painting",
        artist: "Emilie Riggs, United Kingdom",
        medium: "Oil On Canvas",
        size: "50.8 × 40.6 cm",
        price: "C$1,547",
        image: "https://picsum.photos/seed/light-1/520/680",
      },
      {
        id: "light-2",
        title: "Landscape And Birds Painting",
        artist: "Igor Vitoniv, Sweden",
        medium: "Color On Paper",
        size: "100 × 70 cm",
        price: "C$1,785",
        image: "https://picsum.photos/seed/light-2/520/680",
      },
      {
        id: "light-3",
        title: "Infinite Painting",
        artist: "Hennie Van De Lande, Netherlands",
        medium: "Acrylic On Canvas",
        size: "100 × 100 cm",
        price: "C$4,456",
        image: "https://picsum.photos/seed/light-3/520/680",
      },
      {
        id: "light-4",
        title: "Landscape Painting",
        artist: "Marilia Macrida, Italy",
        medium: "Oil On Canvas",
        size: "110 × 120 cm",
        price: "C$4,444",
        image: "https://picsum.photos/seed/light-4/520/680",
      },
      {
        id: "light-5",
        title: "Rose Lake Horizons Painting",
        artist: "Filippo Ioco, Spain",
        medium: "Acrylic On Paper",
        size: "50 × 70 cm",
        price: "C$1,596",
        image: "https://picsum.photos/seed/light-5/520/680",
      },
      {
        id: "light-6",
        title: "Mist Field Painting",
        artist: "Sophie Martin, France",
        medium: "Oil On Canvas",
        size: "90 × 110 cm",
        price: "C$2,930",
        image: "https://picsum.photos/seed/light-6/520/680",
      },
      {
        id: "light-7",
        title: "Pale Dawn Painting",
        artist: "Ava Collins, Australia",
        medium: "Acrylic On Canvas",
        size: "100 × 120 cm",
        price: "C$3,210",
        image: "https://picsum.photos/seed/light-7/520/680",
      },
      {
        id: "light-8",
        title: "Soft Shore Painting",
        artist: "Marco Bellini, Italy",
        medium: "Oil On Linen",
        size: "80 × 100 cm",
        price: "C$2,640",
        image: "https://picsum.photos/seed/light-8/520/680",
      },
      {
        id: "light-9",
        title: "Quiet Pink Sky Painting",
        artist: "Emma Wood, Canada",
        medium: "Acrylic On Canvas",
        size: "75 × 90 cm",
        price: "C$1,980",
        image: "https://picsum.photos/seed/light-9/520/680",
      },
      {
        id: "light-10",
        title: "Still Water Painting",
        artist: "Jonas Meier, Germany",
        medium: "Mixed Media On Canvas",
        size: "95 × 95 cm",
        price: "C$3,840",
        image: "https://picsum.photos/seed/light-10/520/680",
      },
    ],
  },
];
